FROM python:3.8
MAINTAINER 4robed <n.hung19920@gmail.com>

EXPOSE 5000
RUN mkdir -p /app
WORKDIR /app

#RUN pip install pipenv

COPY requirements.txt .
#COPY Pipfile .
#COPY Pipfile.lock .

#RUN pipenv install
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . /app

CMD ["python", "run.py", "celery"]